services:
  - type: web
    name: taxsim-gatsby
    env: static
    branch: production
    buildCommand: gatsby build
    staticPublishPath: public
    headers:
      - path: /*
        name: X-Frame-Options
        value: same-origin
      - path: /*
        name: Referrer-Policy
        value: same-origin
      - path: /*
        name: Feature-Policy
        value: vibrate 'self'; sync-xhr 'self'
      - path: /*
        name: Strict-Transport-Security
        value: max-age=2592000
    routes:
      - type: rewrite
        source: /*
        destination: /index.html`